---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: demo
    image: gcr.io/firstcloudproject-419120/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8000