---
apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app-volume
    image: gcr.io/firstcloudproject-419120/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    volumeMounts:
    - name: data
      mountPath: "/data"
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app